[package]
name = "kzgpad-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[lib]
path = "src/lib.rs"

[[test]]
name = "codec_test"
path = "tests/codec_test.rs"
